import { Building, Heart, Utensils, ShoppingCart, Briefcase, GraduationCap, Hammer } from 'lucide-react';

export const sectors = [
  {
    slug: "artisans-commercants",
    name: "Artisans & Commerçants",
    icon: ShoppingCart,
    heroImage: "/images/sectors/commerce.jpg",
    description: "Solutions informatiques pour optimiser votre gestion, sécuriser vos données et développer votre présence en ligne.",
    challenges: [
      "Gestion des stocks et de la caisse complexe et chronophage",
      "Sécurisation des données clients et des paiements (conformité RGPD et PCI-DSS)",
      "Visibilité en ligne insuffisante face à la concurrence et aux grandes enseignes",
      "Manque de temps pour se former aux outils numériques",
    ],
    solutions: [
      "Mise en place de logiciels de caisse modernes (Lightspeed, Square) et de gestion de stock intégrés",
      "Solutions de sauvegarde automatique et de cybersécurité adaptées aux commerces",
      "Création de site vitrine ou e-commerce avec référencement local (Google My Business)",
      "Formation sur mesure aux outils digitaux (réseaux sociaux, gestion en ligne)",
    ],
  },
  {
    slug: "professions-liberales",
    name: "Professions Libérales",
    icon: Heart,
    heroImage: "/images/sectors/liberal.jpg",
    description: "Confidentialité maximale et outils métier pour les professionnels de santé, du juridique et du conseil.",
    challenges: [
      "Confidentialité absolue des données patients/clients (secret professionnel, RGPD renforcé)",
      "Conformité réglementaire stricte (HDS pour la santé, LPD pour les avocats)",
      "Besoin d'outils métier spécifiques (logiciels médicaux, juridiques, comptables)",
      "Gestion des rendez-vous et de la facturation chronophage",
    ],
    solutions: [
      "Serveurs IA offline pour analyser des documents sensibles sans fuite de données",
      "Sauvegarde sécurisée et chiffrée avec hébergement certifié HDS (Hébergeur de Données de Santé)",
      "Intégration de logiciels métier (Doctolib, Ciel, Sage) avec support dédié",
      "Solutions de téléconsultation et de signature électronique sécurisées",
    ],
  },
  {
    slug: "restaurants-hotels",
    name: "Restaurants & Hôtels",
    icon: Utensils,
    heroImage: "/images/sectors/restaurant.jpg",
    description: "Digitalisez votre établissement pour améliorer l'expérience client et optimiser vos opérations.",
    challenges: [
      "Gestion des réservations et des commandes en temps réel",
      "Réputation en ligne cruciale (avis Google, TripAdvisor, TheFork)",
      "Besoin de systèmes de caisse rapides et fiables (encaissement, tickets)",
      "Coordination cuisine-salle-réception complexe",
    ],
    solutions: [
      "Logiciels de gestion hôtelière (PMS) et de réservation en ligne intégrés",
      "Stratégie de gestion des avis en ligne et de présence digitale (site web, réseaux sociaux)",
      "Systèmes de caisse tactiles et de commande en ligne (Click & Collect, livraison)",
      "Réseau Wi-Fi invité sécurisé et performant pour vos clients",
    ],
  },
  {
    slug: "tpe-pme",
    name: "TPE / PME",
    icon: Briefcase,
    heroImage: "/images/sectors/office.jpg",
    description: "Infrastructure IT complète pour accompagner votre croissance et sécuriser vos opérations.",
    challenges: [
      "Productivité limitée par des outils obsolètes ou mal configurés",
      "Sécurité informatique insuffisante face aux cybermenaces croissantes",
      "Croissance freinée par une infrastructure IT inadaptée",
      "Manque de support technique réactif en cas de panne",
    ],
    solutions: [
      "Audit et modernisation de votre infrastructure IT (serveurs, réseau, postes de travail)",
      "Migration vers le Cloud (Microsoft 365, Google Workspace) pour plus de flexibilité",
      "Support technique dédié avec intervention rapide (24-48h)",
      "Formation de vos équipes aux outils collaboratifs et à la cybersécurité",
    ],
  },
  {
    slug: "associations",
    name: "Associations",
    icon: Building,
    heroImage: "/images/sectors/association.jpg",
    description: "Solutions économiques et performantes adaptées aux budgets associatifs.",
    challenges: [
      "Budget limité pour l'informatique",
      "Gestion des adhérents et des bénévoles complexe",
      "Communication avec les membres et les partenaires chronophage",
      "Besoin de transparence financière et de reporting",
    ],
    solutions: [
      "Solutions open-source et économiques (LibreOffice, Nextcloud, Odoo)",
      "Logiciels de gestion associative (HelloAsso, AssoConnect) avec formation",
      "Site web et newsletter pour communiquer efficacement avec vos membres",
      "Support technique à tarif préférentiel pour les associations",
    ],
  },
  {
    slug: "organismes-formation",
    name: "Organismes de Formation",
    icon: GraduationCap,
    heroImage: "/images/sectors/training.jpg",
    description: "Outils pédagogiques modernes et conformité QUALIOPI pour vos formations.",
    challenges: [
      "Conformité QUALIOPI et gestion administrative lourde",
      "Besoin d'outils pédagogiques modernes (LMS, visioconférence)",
      "Suivi des apprenants et des financements complexe",
      "Digitalisation des formations pour toucher plus de publics",
    ],
    solutions: [
      "Plateforme LMS (Moodle, 360Learning) pour vos formations en ligne",
      "Solutions de visioconférence professionnelles (Zoom, Teams) avec support",
      "Logiciels de gestion des formations (Edof, Dendreo) pour la conformité QUALIOPI",
      "Création de contenus pédagogiques numériques (vidéos, quiz interactifs)",
    ],
  },
  {
    slug: "btp-industrie",
    name: "BTP & Industrie",
    icon: Hammer,
    heroImage: "/images/sectors/construction.jpg",
    description: "Solutions robustes et mobiles pour vos chantiers et sites de production.",
    challenges: [
      "Mobilité des équipes sur les chantiers (accès aux plans, rapports)",
      "Gestion de chantiers et de projets complexe (délais, budgets, ressources)",
      "Besoin de matériel robuste et résistant aux environnements difficiles",
      "Coordination entre bureau et terrain en temps réel",
    ],
    solutions: [
      "Outils mobiles (tablettes durcies, smartphones) pour accéder aux données sur chantier",
      "Logiciels de gestion de chantier (Procore, Buildertrend) avec suivi en temps réel",
      "Réseau robuste et sécurisé pour connecter vos sites distants",
      "Solutions de sauvegarde et de récupération pour protéger vos données critiques",
    ],
  },
];
